//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurMates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public string PersonId { get; set; }
        public string WechatId { get; set; }
        public Nullable<bool> IsClaimed { get; set; }
        public string Name { get; set; }
        public string PictureURL { get; set; }
        public string Location { get; set; }
        public string ElementarySchool { get; set; }
        public string MiddleSchool { get; set; }
        public string HighSchool { get; set; }
        public string University { get; set; }
        public string MasterUniversity { get; set; }
        public string Others { get; set; }
    }
}
