//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurMates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public string PhotoId { get; set; }
        public string PhotoName { get; set; }
        public Nullable<System.DateTime> GraduateDate { get; set; }
        public Nullable<System.DateTime> UploadDateTime { get; set; }
        public Nullable<int> PersonNum { get; set; }
        public string URL { get; set; }
        public string Thumbnail { get; set; }
        public string School { get; set; }
        public string GradeClass { get; set; }
        public string Category { get; set; }
        public string Summary { get; set; }
        public Nullable<int> SchoolLevel { get; set; }
    }
}
